### ISSUE TITLE
Inventaire des machines de la salle serveur

### ISSUE THREAD

**Issue by barodeur** [laplagedigitale/baywatch#2]
## Inventaire

- 1x ordinateur tour
- 1x ordinateur portable Lenovo Thinkpad
- 1x Intel NUC
- 1x NAS Ora Env
- 4x switch Netgear GS724T
- 1x controller ubiquity
- 1x switch ubiquity
- 1x borne wifi ubiquity
- 1x livebox
- 1x modem agora
- 1x router agora

**Comment by thomas-solumy** [comment]
Recommendation du CA : faire un point sur le coût de l'inventaire (énergie + argent)

**Comment by barodeur** [comment]
| Appareil | Quantité | Puissance par unité en W | Puissance Total en W | Commentaire |
|-|-|-|-|-|
| Ordinateur Tour | 1 | 400 |  400 ||
| Ordinateur portable Lenovo Thinkpad | 1 | 60  | 60 ||
| Intel NUC | 1 | 100 | 100 ||
| NAS Ora Env | 1 | 100 | 100 ||
| Switch Netgear GS724T | 4 | 30 | 120 ||
| Controlleur Ubiquity| 1 | 100 | 100 ||
| Borne Ubiquity Wifi| 1 | - | - | Allimenté sur le controlleur |
| Livebox | 1 | 20 | 20 ||
| Modem Agora | 1 | 20 | 20 ||
| Router Agora | 1 | 20 | 20 || 
| **TOTAL** ||| 940 |
